version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-nginx-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/cert.pem:/etc/nginx/cert.pem:ro
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - .env
    environment:
      - REACT_APP_API_BASE_URL=${API_BASE_URL}
      - REACT_APP_DEBUG=${DEBUG}
    restart: always
